name: Install Latest Snapshot to Ubuntu 24.04
on: [push]

jobs:
  Install-Ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    
      - run: wget -O maven-metadata.xml https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/ant-media-server/maven-metadata.xml
        #Get latest snapshot
      - run: | 
         export LATEST_SNAPSHOT=$(cat maven-metadata.xml | grep "<version>" | tail -n 1 |  xargs | cut -c 10-23)
         echo $LATEST_SNAPSHOT
         wget -O ant-media-server-community.zip "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.antmedia&a=ant-media-server&v=${LATEST_SNAPSHOT}&c=community&e=zip";
      - run: ./install_ant-media-server.sh -i ant-media-server-community.zip
      - run: sudo service antmedia status
      - run: sleep 30
      - run: cat /usr/local/antmedia/log/ant-media-server.log
      - run: |
         if [ $(cat /usr/local/antmedia/log/ant-media-server.log | grep "LiveApp started" | wc -l | xargs) -eq 0 ]; then 
           echo "LiveApp started log does not exist. Check the logs above"
           exit 1;
         fi;
      - run: cat /usr/local/antmedia/log/antmedia-error.log
