name:  Install Latest to Ubuntu 20.04
on: [push]
jobs:
  Install-Ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      #Get latest version
      - run: wget -O ant-media-server-community.zip "https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=io.antmedia&a=ant-media-server&v=LATEST&c=community&e=zip";
      - run: ./install_ant-media-server.sh -i ant-media-server-community.zip
      - run: cat /usr/local/antmedia/log/ant-media-server.log
